# 第2章: UNIXコマンド

[popular-names.txt](/data/popular-names.txt)は、アメリカで生まれた赤ちゃんの「名前」「性別」「人数」「年」をタブ区切り形式で格納したファイルである。以下の処理を行うプログラムを作成し、[popular-names.txt](/data/popular-names.txt)を入力ファイルとして実行せよ。さらに、同様の処理をUNIXコマンドでも実行し、プログラムの実行結果を確認せよ。

In [20]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 10. 行数のカウント
ファイルの行数をカウントせよ。確認にはwcコマンドを用いよ。

In [21]:
with open('/content/drive/MyDrive/nlp100/lesson02/popular-names.txt', 'r') as file:
  count = 0
  for line in file:
    count += 1
print(count)

2780

## 11. 先頭からN行を出力
ファイルの先頭N行だけを表示せよ。例えば、N=10として先頭10行を表示せよ。確認にはheadコマンドを用いよ。

In [22]:
with open('/content/drive/MyDrive/nlp100/lesson02/popular-names.txt', 'r') as file:
  lines = file.readlines()
  for i in range(10):
    print(lines[i])

Mary	F	7065	1880

Anna	F	2604	1880

Emma	F	2003	1880

Elizabeth	F	1939	1880

Minnie	F	1746	1880

Margaret	F	1578	1880

Ida	F	1472	1880

Alice	F	1414	1880

Bertha	F	1320	1880

Sarah	F	1288	1880

## 12. 末尾のN行を出力
ファイルの末尾N行だけを表示せよ。例えば、N=10として末尾10行を表示せよ。確認にはtailコマンドを用いよ。

In [23]:
with open('/content/drive/MyDrive/nlp100/lesson02/popular-names.txt', 'r') as file:
  lines = file.readlines()
  for i in range(10):
    print(lines[-i])

Mary	F	7065	1880

Logan	M	12352	2018

Mason	M	12435	2018

Lucas	M	12585	2018

Elijah	M	12886	2018

Benjamin	M	13381	2018

Oliver	M	13389	2018

James	M	13525	2018

William	M	14516	2018

Noah	M	18267	2018

## 13. タブをスペースに置換
ファイルの先頭10行に対して、タブ1文字につきスペース1文字に置換して出力せよ。確認にはsedコマンド、trコマンド、もしくはexpandコマンドなどを用いよ。

In [24]:
import re

In [25]:
with open('/content/drive/MyDrive/nlp100/lesson02/popular-names.txt', 'r') as file:
  lines = file.readlines()
  for i in range(10):
    line = lines[i]
    line = re.sub('\t', ' ', line)
    print(line)

Mary F 7065 1880

Anna F 2604 1880

Emma F 2003 1880

Elizabeth F 1939 1880

Minnie F 1746 1880

Margaret F 1578 1880

Ida F 1472 1880

Alice F 1414 1880

Bertha F 1320 1880

Sarah F 1288 1880

## 14. 1列目を出力
ファイルの先頭10行に対して、各行の1列目だけを抜き出して表示せよ。確認にはcutコマンドなどを用いよ。

In [26]:
with open('/content/drive/MyDrive/nlp100/lesson02/popular-names.txt', 'r') as file:
  lines = file.readlines()
  for i in range(10):
    print(re.split('\t', lines[i])[0])

Mary
Anna
Emma
Elizabeth
Minnie
Margaret
Ida
Alice
Bertha
Sarah

## 15. ファイルをN分割する
ファイルを行単位でN分割し、別のファイルに格納せよ。例えば、N=10としてファイルを10分割せよ。同様の処理をsplitコマンドで実現せよ。

In [32]:
with open('/content/drive/MyDrive/nlp100/lesson02/popular-names.txt', 'r') as file:
  count = 0
  lines = file.readlines()
  for i in range(0, len(lines), len(lines)//10):
    with open(f'/content/drive/MyDrive/nlp100/lesson02/data/split-{count}.txt', 'w') as file:
      file.write(''.join(lines[i:i+len(lines)//10]))
    count += 1
print(count)

10

## 16. ランダムに各行を並び替える
ファイルを行単位でランダムに並び替えよ（注意: 各行の内容は変更せずに並び替えよ）。同様の処理をshufコマンドで実現せよ。

In [33]:
import random

In [35]:
with open('/content/drive/MyDrive/nlp100/lesson02/popular-names.txt', 'r') as file:
  lines = file.readlines()
  random.shuffle(lines)
  with open('/content/drive/MyDrive/nlp100/lesson02/data/random.txt', 'w') as file:
    file.write(''.join(lines))

## 17. １列目の文字列の異なり
1列目の文字列の異なり（文字列の種類）を求めよ。確認にはcut, sort, uniqコマンドを用いよ。

In [36]:
import pandas as pd

In [82]:
data = {'Name': [], 'Sex': [], 'Population': [], 'Year': []}
with open('/content/drive/MyDrive/nlp100/lesson02/popular-names.txt', 'r') as file:
  lines = file.readlines()
  for line in lines:
    line = re.sub('\n', '', line)
    line = re.split('\t', line)
    data['Name'].append(line[0])
    data['Sex'].append(line[1])
    data['Population'].append(line[2])
    data['Year'].append(line[3])

df = pd.DataFrame(data)
unique = df['Name'].unique()
print(len(unique))
unique

136

array(['Mary', 'Anna', 'Emma', 'Elizabeth', 'Minnie', 'Margaret', 'Ida',
       'Alice', 'Bertha', 'Sarah', 'John', 'William', 'James', 'Charles',
       'George', 'Frank', 'Joseph', 'Thomas', 'Henry', 'Robert', 'Annie',
       'Edward', 'Clara', 'Florence', 'Ethel', 'Bessie', 'Harry', 'Helen',
       'Ruth', 'Marie', 'Lillian', 'Mildred', 'Dorothy', 'Frances',
       'Walter', 'Evelyn', 'Virginia', 'Richard', 'Betty', 'Donald',
       'Doris', 'Shirley', 'Barbara', 'Patricia', 'Joan', 'Nancy',
       'Carol', 'David', 'Ronald', 'Judith', 'Linda', 'Sandra', 'Carolyn',
       'Sharon', 'Michael', 'Susan', 'Donna', 'Larry', 'Kathleen',
       'Deborah', 'Gary', 'Karen', 'Debra', 'Pamela', 'Cynthia', 'Mark',
       'Steven', 'Lisa', 'Jeffrey', 'Lori', 'Kimberly', 'Tammy', 'Angela',
       'Michelle', 'Jennifer', 'Melissa', 'Christopher', 'Brian', 'Amy',
       'Laura', 'Tracy', 'Julie', 'Jason', 'Scott', 'Stephanie',
       'Heather', 'Nicole', 'Matthew', 'Rebecca', 'Jessica', 'Amanda',
       'Daniel', 'Kelly', 'Joshua', 'Crystal', 'Ashley', 'Megan',
       'Brittany', 'Andrew', 'Justin', 'Samantha', 'Lauren', 'Emily',
       'Brandon', 'Tyler', 'Taylor', 'Nicholas', 'Jacob', 'Hannah',
       'Austin', 'Alexis', 'Rachel', 'Madison', 'Abigail', 'Olivia',
       'Ethan', 'Anthony', 'Isabella', 'Ava', 'Sophia', 'Chloe',
       'Alexander', 'Mia', 'Jayden', 'Noah', 'Aiden', 'Mason', 'Liam',
       'Charlotte', 'Harper', 'Benjamin', 'Elijah', 'Amelia', 'Logan',
       'Oliver', 'Lucas'], dtype=object)

## 18. 各行の1列目の文字列の出現頻度を求め、出現頻度の高い順に並べる
1列目の文字列の出現頻度を求め、出現頻度と名前を出現頻度の多い順に並べて表示せよ。確認にはcut, uniq, sortコマンドを用いよ。

In [83]:
data = {'Name': [], 'Sex': [], 'Population': [], 'Year': []}
with open('/content/drive/MyDrive/nlp100/lesson02/popular-names.txt', 'r') as file:
  lines = file.readlines()
  for line in lines:
    line = re.sub('\n', '', line)
    line = re.split('\t', line)
    data['Name'].append(line[0])
    data['Sex'].append(line[1])
    data['Population'].append(line[2])
    data['Year'].append(line[3])

df = pd.DataFrame(data)
df = df.groupby('Name').count()
df['Count'] = df['Sex']
df = df[['Count']]
df = df.sort_values(by = 'Count', ascending = False)
df

         Count
Name
James      118
William    111
John       108
Robert     108
Mary        92
...        ...
Pamela       1
Rachel       1
Scott        1
Tracy        1
Walter       1

[136 rows x 1 columns]

## 19. 3列目の数値の降順に各行を並び替える
3列目の数値の逆順でファイルの各行を整列せよ（注意: 各行の内容は変更せずに並び替えよ）。同様の処理をsortコマンドで実現せよ。

In [87]:
data = {'Name': [], 'Sex': [], 'Population': [], 'Year': []}
with open('/content/drive/MyDrive/nlp100/lesson02/popular-names.txt', 'r') as file:
  lines = file.readlines()
  for line in lines:
    line = re.sub('\n', '', line)
    line = re.split('\t', line)
    data['Name'].append(line[0])
    data['Sex'].append(line[1])
    data['Population'].append(int(line[2]))
    data['Year'].append(int(line[3]))

df = pd.DataFrame(data)
df = df.sort_values(by = 'Population', ascending = False)
df

         Name Sex  Population  Year
1340    Linda   F       99689  1947
1360    Linda   F       96211  1948
1350    James   M       94757  1947
1550  Michael   M       92704  1957
1351   Robert   M       91640  1947
...       ...  ..         ...   ...
27      Annie   F        1326  1881
28     Bertha   F        1324  1881
8      Bertha   F        1320  1880
29      Alice   F        1308  1881
9       Sarah   F        1288  1880

[2780 rows x 4 columns]